/**
 * © 2026 Fernando Rodrigues de Jácomo.
 * Produzido no âmbito do Projeto Comunitário de Milreu.
 * Consultar RIGHTS.md.
 */
export const languages = ["pt-PT", "en", "es", "fr"];

const ui = {
  "pt-PT": { project:"Projeto", initiatives:"Iniciativas", museum:"Museu", knowledge:"Conhecimento", participate:"Participar", explore:"Explorar", timeline:"Linha temporal", backProject:"Voltar ao Projeto", homeTitle:"Projeto Comunitário de Milreu", homeLead:"Memórias, conhecimento e participação em torno de Milreu.", enterMuseum:"Entrar no Museu", discoverProject:"Conhecer o projeto", museumTitle:"Museu de Memórias de Milreu", museumLead:"Uma experiência visual sobre as relações entre pessoas, comunidade, paisagem, Estoi e Milreu.", gallery:"Memórias", search:"Pesquisar", period:"Período", type:"Tipo", all:"Todos", results:"registos", community:"Narrativa comunitária", context:"Contexto", objective:"Descrição", provenance:"Proveniência e créditos", rights:"Direitos e publicação", relations:"Memórias relacionadas", fullscreen:"Ecrã inteiro", close:"Fechar", previous:"Anterior", next:"Seguinte", unavailable:"Este registo não está disponível no site", unavailableText:"A imagem permanece no repositório para auditoria, mas está bloqueada na experiência pública devido à natureza da intervenção digital.", returnGallery:"Regressar à galeria", fallback:"Texto apresentado em português por ausência de tradução revista.", preliminary:"Pré-visualização editorial", noResults:"Nenhuma memória corresponde aos filtros.", portalFeature:"O portal orienta", museumFeature:"O museu imerge", proteusFeature:"Proteus estrutura", portalFeatureText:"Um ponto de entrada para o projeto, iniciativas, conhecimento e participação.", museumFeatureText:"Fotografias, narrativas, contexto e relações numa exploração visual.", proteusFeatureText:"A mesma fonte de dados alimentará o site, os totens e futuras aplicações.", featured:"Algumas memórias", featuredLead:"A primeira fatia vertical já utiliza as fotografias autorizadas e os registos migrados.", viewAll:"Ver todas as memórias", notFound:"Página não encontrada" },
  en: { project:"Project", initiatives:"Initiatives", museum:"Museum", knowledge:"Knowledge", participate:"Participate", explore:"Explore", timeline:"Timeline", backProject:"Back to Project", homeTitle:"Milreu Community Project", homeLead:"Memories, knowledge and participation around Milreu.", enterMuseum:"Enter the Museum", discoverProject:"Discover the project", museumTitle:"Milreu Museum of Memories", museumLead:"A visual experience about relationships between people, community, landscape, Estoi and Milreu.", gallery:"Memories", search:"Search", period:"Period", type:"Type", all:"All", results:"records", community:"Community narrative", context:"Context", objective:"Description", provenance:"Provenance and credits", rights:"Rights and publication", relations:"Related memories", fullscreen:"Fullscreen", close:"Close", previous:"Previous", next:"Next", unavailable:"This record is not available on the site", unavailableText:"The image remains in the repository for audit, but is blocked from the public experience because of the nature of the digital intervention.", returnGallery:"Return to gallery", fallback:"Portuguese text shown because no reviewed translation is available.", preliminary:"Editorial preview", noResults:"No memory matches the filters.", portalFeature:"The portal guides", museumFeature:"The museum immerses", proteusFeature:"Proteus structures", portalFeatureText:"A gateway to the project, initiatives, knowledge and participation.", museumFeatureText:"Photographs, narratives, context and relations in a visual exploration.", proteusFeatureText:"The same data source will feed the site, physical totems and future applications.", featured:"Selected memories", featuredLead:"The first vertical slice already uses authorised photographs and migrated records.", viewAll:"View all memories", notFound:"Page not found" },
  es: { project:"Proyecto", initiatives:"Iniciativas", museum:"Museo", knowledge:"Conocimiento", participate:"Participar", explore:"Explorar", timeline:"Cronología", backProject:"Volver al Proyecto", homeTitle:"Proyecto Comunitario de Milreu", homeLead:"Memorias, conocimiento y participación en torno a Milreu.", enterMuseum:"Entrar en el Museo", discoverProject:"Conocer el proyecto", museumTitle:"Museo de Memorias de Milreu", museumLead:"Una experiencia visual sobre las relaciones entre personas, comunidad, paisaje, Estoi y Milreu.", gallery:"Memorias", search:"Buscar", period:"Periodo", type:"Tipo", all:"Todos", results:"registros", community:"Narrativa comunitaria", context:"Contexto", objective:"Descripción", provenance:"Procedencia y créditos", rights:"Derechos y publicación", relations:"Memorias relacionadas", fullscreen:"Pantalla completa", close:"Cerrar", previous:"Anterior", next:"Siguiente", unavailable:"Este registro no está disponible en el sitio", unavailableText:"La imagen permanece en el repositorio para auditoría, pero está bloqueada en la experiencia pública por la naturaleza de la intervención digital.", returnGallery:"Volver a la galería", fallback:"Texto en portugués por falta de traducción revisada.", preliminary:"Vista previa editorial", noResults:"Ninguna memoria coincide con los filtros.", portalFeature:"El portal orienta", museumFeature:"El museo sumerge", proteusFeature:"Proteus estructura", portalFeatureText:"Una entrada al proyecto, iniciativas, conocimiento y participación.", museumFeatureText:"Fotografías, narrativas, contexto y relaciones en una exploración visual.", proteusFeatureText:"La misma fuente de datos alimentará el sitio, los tótems y futuras aplicaciones.", featured:"Algunas memorias", featuredLead:"La primera sección funcional ya utiliza fotografías autorizadas y registros migrados.", viewAll:"Ver todas las memorias", notFound:"Página no encontrada" },
  fr: { project:"Projet", initiatives:"Initiatives", museum:"Musée", knowledge:"Connaissance", participate:"Participer", explore:"Explorer", timeline:"Chronologie", backProject:"Retour au Projet", homeTitle:"Projet Communautaire de Milreu", homeLead:"Mémoires, connaissances et participation autour de Milreu.", enterMuseum:"Entrer dans le Musée", discoverProject:"Découvrir le projet", museumTitle:"Musée des Mémoires de Milreu", museumLead:"Une expérience visuelle sur les relations entre les personnes, la communauté, le paysage, Estoi et Milreu.", gallery:"Mémoires", search:"Rechercher", period:"Période", type:"Type", all:"Tous", results:"notices", community:"Récit communautaire", context:"Contexte", objective:"Description", provenance:"Provenance et crédits", rights:"Droits et publication", relations:"Mémoires associées", fullscreen:"Plein écran", close:"Fermer", previous:"Précédente", next:"Suivante", unavailable:"Cette notice n’est pas disponible sur le site", unavailableText:"L’image reste dans le dépôt pour audit, mais elle est bloquée dans l’expérience publique en raison de la nature de l’intervention numérique.", returnGallery:"Retour à la galerie", fallback:"Texte portugais affiché faute de traduction révisée.", preliminary:"Aperçu éditorial", noResults:"Aucune mémoire ne correspond aux filtres.", portalFeature:"Le portail oriente", museumFeature:"Le musée immerge", proteusFeature:"Proteus structure", portalFeatureText:"Une porte d’entrée vers le projet, les initiatives, les connaissances et la participation.", museumFeatureText:"Photographies, récits, contexte et relations dans une exploration visuelle.", proteusFeatureText:"La même source de données alimentera le site, les totems et les futures applications.", featured:"Quelques mémoires", featuredLead:"La première tranche fonctionnelle utilise déjà les photographies autorisées et les notices migrées.", viewAll:"Voir toutes les mémoires", notFound:"Page introuvable" }
};

export const text = (lang, key) => ui[lang]?.[key] ?? ui["pt-PT"][key] ?? key;
export function localised(value, lang) {
  if (!value || typeof value !== "object") return { value: value ?? "", fallback: false };
  const selected = value[lang];
  if (selected) return { value: selected, fallback: false };
  return { value: value["pt-PT"] ?? "", fallback: lang !== "pt-PT" };
}
