/**
 * © 2026 Fernando Rodrigues de Jácomo.
 * Produzido no âmbito do Projeto Comunitário de Milreu.
 * Consultar RIGHTS.md.
 */
import { loadCollaborativeConfig, loadCollaborativeFoundationData, callbackUrl } from "./config.js";
import { createCollaborativeSupabaseClient } from "./supabase-client.js";
import { expandRolePermissions, visibleModules, hasPermission } from "./permissions.js";

const DEMO_KEY="milreu-collaborative-demo-context-v4";

function emptyManagement(){return{members:[],requests:[],invitations:[],notes:[],audit:[]};}
function emptyTaskWorkspace(){return{tasks:[],assignments:[],requiredSkills:[],preferences:null,availability:[],timeEntries:[],updates:[]};}
function emptyExhibitionWorkspace(){return{venues:[],exhibitions:[],schedules:[],events:[],participants:[],checklist:[],conflicts:[]};}
function emptyContext(){return{ready:false,mode:"demo",authenticated:false,session:null,profile:null,membership:null,accessRequest:null,roles:[],permissions:[],modules:[],profileTypes:[],moduleRegistry:[],roleRegistry:[],permissionRegistry:[],memberCatalog:{interestAreas:[],skills:[],languages:[]},taskModel:{categories:[],taskStatuses:[],assignmentStatuses:[],assignmentModes:[],locationModes:[],priorities:[],availabilityModes:[],weekdays:[]},exhibitionModel:{exhibitionTypes:[],exhibitionStatuses:[],venueTypes:[],scheduleStatuses:[],installationStatuses:[],logisticsStatuses:[],eventTypes:[],eventStatuses:[],visibilityOptions:[],rsvpStatuses:[],checklistCategories:[]},management:emptyManagement(),taskWorkspace:emptyTaskWorkspace(),exhibitionWorkspace:emptyExhibitionWorkspace(),tasks:[],exhibitions:[],error:null,notice:null};}
function demoAudit(action,userId,actor="demo-master",metadata={}){return{id:`demo-audit-${Date.now()}-${Math.random()}`,actor_user_id:actor,action,entity_type:"membership",entity_id:userId,metadata,created_at:new Date().toISOString()};}
function daysFromNow(days,hour=10){const d=new Date();d.setDate(d.getDate()+days);d.setHours(hour,0,0,0);return d.toISOString();}
function demoTaskUpdate(taskId,userId,type,note="",metadata={}){return{id:`demo-update-${Date.now()}-${Math.random()}`,project_id:"demo-project",task_id:taskId,user_id:userId,update_type:type,note,metadata,created_at:new Date().toISOString()};}

function dateFromNow(days){return daysFromNow(days,12).slice(0,10);}
function createDemoExhibitionWorkspace(){
  const venues=[
    {id:"demo-venue-cultural",project_id:"demo-project",name:"Espaço Cultural de demonstração",slug:"espaco-cultural-demonstracao",venue_type:"cultural-centre",municipality:"Faro",locality:"Localidade de demonstração",address_text:"Morada fictícia para avaliação",country_code:"PT",postal_code:null,public_email:null,public_phone:null,public_url:null,opening_hours:"Horário de demonstração",public_description:"Local fictício utilizado apenas para testar a gestão da itinerância.",accessibility_summary:"Informação de acessibilidade por validar.",accessibility_notes:"Dado de demonstração.",internal_notes:"Não corresponde a um local real.",status:"active",public_visibility:true,active:true},
    {id:"demo-venue-school",project_id:"demo-project",name:"Escola de demonstração",slug:"escola-demonstracao",venue_type:"school",municipality:"Faro",locality:"Localidade de demonstração",address_text:null,country_code:"PT",postal_code:null,public_description:null,accessibility_summary:null,internal_notes:"Local de demonstração ainda em contacto.",status:"draft",public_visibility:false,active:true}
  ];
  const exhibitions=[
    {id:"demo-exhibition-itinerant",project_id:"demo-project",title:"Entre Ruínas e Memórias — demonstração",slug:"entre-ruinas-memorias-demonstracao",subtitle:"Exposição comunitária itinerante",exhibition_type:"itinerant",description:"Registo fictício para avaliar o fluxo de itinerância.",public_summary:"Exposição de demonstração sem correspondência com datas ou locais reais.",internal_objectives:"Testar calendário, publicação, logística e voluntariado.",status:"active",default_duration_days:14,public_visibility:true,published_at:new Date().toISOString()}
  ];
  const schedules=[
    {id:"demo-schedule-current",project_id:"demo-project",exhibition_id:"demo-exhibition-itinerant",venue_id:"demo-venue-cultural",slug:"demonstracao-local-atual",starts_on:dateFromNow(-3),ends_on:dateFromNow(7),status:"open",installation_at:daysFromNow(-4,9),dismantling_at:daysFromNow(8,9),public_title:"Exposição em local de demonstração",public_summary:"Período fictício para avaliação do calendário.",public_notes:"Não corresponde a uma exposição real.",internal_notes:"Validar a experiência de coordenação.",public_visibility:true,published_at:new Date().toISOString(),opening_hours:"Horário de demonstração",public_contact:null,registration_url:null,installation_status:"checked",logistics_status:"in-progress",transport_notes:"Notas fictícias.",condition_report_before:"Verificação de demonstração concluída.",condition_report_after:null},
    {id:"demo-schedule-future",project_id:"demo-project",exhibition_id:"demo-exhibition-itinerant",venue_id:"demo-venue-school",slug:"demonstracao-proximo-local",starts_on:dateFromNow(30),ends_on:dateFromNow(44),status:"planned",installation_at:daysFromNow(29,9),dismantling_at:daysFromNow(45,9),public_title:null,public_summary:null,public_notes:null,internal_notes:"Período ainda não confirmado.",public_visibility:false,published_at:null,opening_hours:null,public_contact:null,registration_url:null,installation_status:"not-started",logistics_status:"not-started",transport_notes:null,condition_report_before:null,condition_report_after:null}
  ];
  const events=[
    {id:"demo-event-opening",project_id:"demo-project",exhibition_schedule_id:"demo-schedule-current",venue_id:"demo-venue-cultural",title:"Abertura de demonstração",description:"Evento fictício para testar confirmações de participação.",event_type:"opening",status:"confirmed",visibility:"public",starts_at:daysFromNow(1,18),ends_at:daysFromNow(1,20),location_text:"Espaço Cultural de demonstração",capacity:30,registration_required:false,registration_url:null,public_contact:null},
    {id:"demo-event-dismantling",project_id:"demo-project",exhibition_schedule_id:"demo-schedule-current",venue_id:"demo-venue-cultural",title:"Apoio à desmontagem — demonstração",description:"Atividade interna fictícia.",event_type:"dismantling",status:"confirmed",visibility:"members",starts_at:daysFromNow(8,9),ends_at:daysFromNow(8,13),location_text:"Espaço Cultural de demonstração",capacity:6,registration_required:true,registration_url:null,public_contact:null}
  ];
  const participants=[
    {event_id:"demo-event-opening",user_id:"demo-volunteer",status:"attending",notes:null,responded_at:new Date().toISOString()}
  ];
  const checklist=[
    {id:"demo-check-transport",project_id:"demo-project",schedule_id:"demo-schedule-current",category:"transport",title:"Confirmar transporte dos painéis",description:"Item fictício.",status:"in-progress",assigned_to:"demo-master",due_at:daysFromNow(6,18),sort_order:10},
    {id:"demo-check-accessibility",project_id:"demo-project",schedule_id:"demo-schedule-current",category:"accessibility",title:"Verificar circulação e altura dos textos",description:"Item fictício.",status:"pending",assigned_to:null,due_at:daysFromNow(6,18),sort_order:20},
    {id:"demo-check-condition",project_id:"demo-project",schedule_id:"demo-schedule-current",category:"condition",title:"Registar estado antes da desmontagem",description:"Item fictício.",status:"pending",assigned_to:null,due_at:daysFromNow(7,18),sort_order:30}
  ];
  return{venues,exhibitions,schedules,events,participants,checklist,conflicts:[]};
}

function createDemoTaskWorkspace(){
  const tasks=[
    {id:"demo-task-digitisation",project_id:"demo-project",title:"Digitalizar fotografias do arquivo comunitário",summary:"Preparar imagens e verificar nomes de ficheiros para futura catalogação.",description:"Digitalização e controlo técnico de um pequeno conjunto de fotografias de demonstração.",instructions:"Utilizar apenas os materiais indicados pela coordenação. Não publicar ficheiros fora do projeto.",category:"digitisation",category_code:"digitisation",status:"open",priority:"high",assignment_mode:"approval",location_mode:"hybrid",location_name:"Área Colaborativa",municipality:"Faro",starts_at:daysFromNow(2,9),due_at:daysFromNow(14,18),application_deadline:daysFromNow(7,18),estimated_minutes:240,capacity:3,minimum_participants:1,visibility:"members",recognition_eligible:true,created_by:"demo-master",updated_at:new Date().toISOString()},
    {id:"demo-task-exhibition",project_id:"demo-project",title:"Apoiar a preparação da exposição itinerante",summary:"Rever materiais, checklist e necessidades de montagem.",description:"Atividade de demonstração para testar tarefas presenciais e convites diretos.",instructions:"A data e o local são fictícios e servem apenas para avaliação do módulo.",category:"exhibition-setup",category_code:"exhibition-setup",status:"open",priority:"normal",assignment_mode:"direct",location_mode:"on-site",location_name:"Local de demonstração",municipality:"Faro",starts_at:daysFromNow(9,9),due_at:daysFromNow(9,17),application_deadline:null,estimated_minutes:360,capacity:4,minimum_participants:2,visibility:"members",recognition_eligible:true,created_by:"demo-master",updated_at:new Date().toISOString()},
    {id:"demo-task-transcription",project_id:"demo-project",title:"Rever uma transcrição de entrevista",summary:"Comparar a transcrição com o áudio e assinalar dúvidas.",description:"Atividade remota de demonstração para testar acompanhamento e conclusão.",instructions:"Não copiar o conteúdo para serviços externos.",category:"transcription",category_code:"transcription",status:"in-progress",priority:"normal",assignment_mode:"approval",location_mode:"remote",location_name:null,municipality:null,starts_at:daysFromNow(-2,9),due_at:daysFromNow(5,18),application_deadline:daysFromNow(-3,18),estimated_minutes:180,capacity:2,minimum_participants:1,visibility:"members",recognition_eligible:true,created_by:"demo-master",updated_at:new Date().toISOString()},
    {id:"demo-task-draft",project_id:"demo-project",title:"Preparar roteiro de acolhimento de voluntários",summary:"Rascunho visível apenas para coordenação.",description:"Exemplo de tarefa ainda não publicada.",instructions:null,category:"event-support",category_code:"event-support",status:"draft",priority:"low",assignment_mode:"approval",location_mode:"flexible",location_name:null,municipality:null,starts_at:null,due_at:daysFromNow(30,18),application_deadline:null,estimated_minutes:120,capacity:2,minimum_participants:1,visibility:"members",recognition_eligible:false,created_by:"demo-master",updated_at:new Date().toISOString()}
  ];
  const assignments=[
    {task_id:"demo-task-digitisation",user_id:"demo-volunteer",status:"applied",applied_at:new Date().toISOString(),application_note:"Tenho experiência em digitalização e disponibilidade ao sábado.",updated_at:new Date().toISOString()},
    {task_id:"demo-task-exhibition",user_id:"demo-volunteer",status:"invited",assigned_by:"demo-master",assigned_at:new Date().toISOString(),manager_note:"Convite de demonstração.",updated_at:new Date().toISOString()},
    {task_id:"demo-task-transcription",user_id:"demo-volunteer",status:"in-progress",accepted_at:daysFromNow(-3,10),started_at:daysFromNow(-2,10),updated_at:new Date().toISOString()}
  ];
  const requiredSkills=[
    {task_id:"demo-task-digitisation",skill_code:"digitisation",required:true},
    {task_id:"demo-task-digitisation",skill_code:"cataloguing",required:false},
    {task_id:"demo-task-exhibition",skill_code:"installation",required:false},
    {task_id:"demo-task-exhibition",skill_code:"event-support",required:false},
    {task_id:"demo-task-transcription",skill_code:"transcription",required:true}
  ];
  const preferences={project_id:"demo-project",user_id:"demo-volunteer",preferred_modes:["remote","on-site"],maximum_weekly_minutes:360,availability_notes:"Disponibilidade de demonstração.",timezone:"Europe/Lisbon"};
  const availability=[
    {id:"demo-slot-1",project_id:"demo-project",user_id:"demo-volunteer",day_of_week:6,starts_at:"09:00:00",ends_at:"13:00:00",mode:"hybrid",active:true},
    {id:"demo-slot-2",project_id:"demo-project",user_id:"demo-volunteer",day_of_week:3,starts_at:"19:00:00",ends_at:"21:00:00",mode:"remote",active:true}
  ];
  const timeEntries=[{id:"demo-time-1",project_id:"demo-project",task_id:"demo-task-transcription",user_id:"demo-volunteer",activity_date:new Date().toISOString().slice(0,10),minutes:45,note:"Primeira revisão.",status:"pending",created_at:new Date().toISOString()}];
  const updates=[demoTaskUpdate("demo-task-digitisation","demo-volunteer","application","Candidatura de demonstração."),demoTaskUpdate("demo-task-exhibition","demo-volunteer","invitation","Convite de demonstração."),demoTaskUpdate("demo-task-transcription","demo-volunteer","started","Atividade iniciada.")];
  return{tasks,assignments,requiredSkills,preferences,availability,timeEntries,updates};
}

class CollaborativeController{
  constructor(){this.state=emptyContext();this.listeners=new Set();this.config=null;this.foundation=null;this.client=null;this.authSubscription=null;}
  getState(){return structuredClone(this.state);}
  subscribe(listener){this.listeners.add(listener);return()=>this.listeners.delete(listener);}
  emit(){const snapshot=this.getState();for(const listener of this.listeners)listener(snapshot);}

  async init(){
    this.config=await loadCollaborativeConfig();
    this.foundation=await loadCollaborativeFoundationData();
    this.state={...emptyContext(),ready:false,mode:this.config.mode,profileTypes:this.foundation.profileTypes,moduleRegistry:this.foundation.modules,roleRegistry:this.foundation.roles,permissionRegistry:this.foundation.permissions,memberCatalog:this.foundation.memberCatalog,taskModel:this.foundation.taskModel,exhibitionModel:this.foundation.exhibitionModel};
    if(this.config.mode==="supabase"){
      this.client=await createCollaborativeSupabaseClient(this.config);
      const{data,error}=await this.client.auth.getSession();if(error)this.state.error=error.message;if(data?.session)await this.loadRemoteContext(data.session);
      const{data:subscription}=this.client.auth.onAuthStateChange(async(_event,session)=>{if(session)await this.loadRemoteContext(session);else this.resetAuthentication();this.emit();});this.authSubscription=subscription?.subscription||null;
    }else this.loadDemoContext();
    this.state.ready=true;this.emit();return this.getState();
  }

  resetAuthentication(){Object.assign(this.state,{authenticated:false,session:null,profile:null,membership:null,accessRequest:null,roles:[],permissions:[],modules:[],management:emptyManagement(),taskWorkspace:emptyTaskWorkspace(),exhibitionWorkspace:emptyExhibitionWorkspace(),tasks:[],exhibitions:[],error:null});}

  async loadRemoteContext(session){
    this.state.session={user:{id:session.user.id,email:session.user.email,user_metadata:session.user.user_metadata||{}}};this.state.authenticated=true;
    const{data,error}=await this.client.rpc("collab_get_my_context");if(error){this.state.error=error.message;return;}
    this.state.profile=data.profile||{user_id:session.user.id,email:session.user.email,display_name:session.user.user_metadata?.full_name||session.user.user_metadata?.name||"",avatar_url:session.user.user_metadata?.avatar_url||session.user.user_metadata?.picture||null,primary_profile_type:null,locale:"pt-PT"};
    this.state.membership=data.membership||{status:"pending"};this.state.accessRequest=data.accessRequest||null;this.state.roles=data.roles||[];this.state.permissions=data.permissions||[];this.state.modules=data.modules||visibleModules(this.state,this.foundation.modules);this.state.error=null;
    await this.loadRemoteOwnPreferences();
    if(hasPermission(this.state,"memberships.view")||hasPermission(this.state,"memberships.manage"))await this.loadRemoteManagement();
    if(hasPermission(this.state,"tasks.view")||hasPermission(this.state,"tasks.manage"))await this.loadRemoteTasks();
    if(hasPermission(this.state,"agenda.view"))await this.loadRemoteExhibitions();
  }

  async loadRemoteOwnPreferences(){
    const userId=this.state.session?.user?.id;if(!userId)return;
    const[interests,skills]=await Promise.all([this.client.from("collab_member_interests").select("interest_code").eq("user_id",userId),this.client.from("collab_member_skills").select("skill_code,level").eq("user_id",userId)]);
    if(!interests.error)this.state.profile.interests=(interests.data||[]).map(x=>x.interest_code);
    if(!skills.error)this.state.profile.skills=(skills.data||[]).map(x=>x.skill_code);
  }

  async loadRemoteManagement(){
    const jobs=[
      this.client.from("collab_profiles").select("user_id,email,display_name,preferred_name,primary_profile_type,avatar_url,organization_name,languages,profile_completed_at,updated_at").order("display_name"),
      this.client.from("collab_project_memberships").select("project_id,user_id,status,primary_profile_type,requested_at,approved_at,approved_by,suspended_at,notes"),
      this.client.from("collab_access_requests").select("id,user_id,requested_profile_type,motivation,status,submitted_at,reviewed_at,reviewer_notes").order("submitted_at",{ascending:false}),
      this.client.from("collab_member_roles").select("user_id,role_code,assigned_at,assigned_by"),
      this.client.from("collab_access_invitations").select("id,email,intended_profile_type,role_codes,status,expires_at,internal_notes,created_by,created_at,claimed_by,claimed_at,revoked_at").order("created_at",{ascending:false}),
      this.client.from("collab_membership_notes").select("id,user_id,note,visibility,created_by,created_at").order("created_at",{ascending:false}),
      this.client.from("collab_audit_log").select("id,actor_user_id,action,entity_type,entity_id,metadata,created_at").order("created_at",{ascending:false}).limit(300),
      this.client.from("collab_member_interests").select("user_id,interest_code"),this.client.from("collab_member_skills").select("user_id,skill_code,level")
    ];
    const[profiles,memberships,requests,roles,invitations,notes,audit,interests,skills]=await Promise.all(jobs);const error=[profiles,memberships,requests,roles,invitations,notes,audit,interests,skills].find(x=>x.error)?.error;if(error){this.state.error=error.message;return;}
    const membershipMap=new Map((memberships.data||[]).map(x=>[x.user_id,x])),rolesMap=new Map(),interestMap=new Map(),skillMap=new Map();
    for(const x of roles.data||[]){const a=rolesMap.get(x.user_id)||[];a.push(x.role_code);rolesMap.set(x.user_id,a);}for(const x of interests.data||[]){const a=interestMap.get(x.user_id)||[];a.push(x.interest_code);interestMap.set(x.user_id,a);}for(const x of skills.data||[]){const a=skillMap.get(x.user_id)||[];a.push(x.skill_code);skillMap.set(x.user_id,a);}
    this.state.management={members:(profiles.data||[]).map(profile=>({...profile,membership:membershipMap.get(profile.user_id)||null,roles:rolesMap.get(profile.user_id)||[],interests:interestMap.get(profile.user_id)||[],skills:skillMap.get(profile.user_id)||[]})),requests:requests.data||[],invitations:invitations.data||[],notes:notes.data||[],audit:audit.data||[]};
  }

  async loadRemoteTasks(){
    const userId=this.state.session?.user?.id;if(!userId)return;
    const jobs=[
      this.client.from("collab_tasks").select("*").order("due_at",{ascending:true}),
      this.client.from("collab_task_assignments").select("*").order("updated_at",{ascending:false}),
      this.client.from("collab_task_required_skills").select("task_id,skill_code,required"),
      this.client.from("collab_volunteer_preferences").select("*").eq("user_id",userId).limit(1),
      this.client.from("collab_member_availability").select("*").eq("user_id",userId).eq("active",true).order("day_of_week").order("starts_at"),
      this.client.from("collab_task_time_entries").select("*").order("activity_date",{ascending:false}),
      this.client.from("collab_task_updates").select("*").order("created_at",{ascending:false}).limit(500)
    ];
    const[tasks,assignments,requiredSkills,preferences,availability,timeEntries,updates]=await Promise.all(jobs);const error=[tasks,assignments,requiredSkills,preferences,availability,timeEntries,updates].find(x=>x.error)?.error;if(error){this.state.error=error.message;return;}
    this.state.taskWorkspace={tasks:tasks.data||[],assignments:assignments.data||[],requiredSkills:requiredSkills.data||[],preferences:preferences.data?.[0]||null,availability:availability.data||[],timeEntries:timeEntries.data||[],updates:updates.data||[]};this.state.tasks=this.state.taskWorkspace.tasks;
  }

  async loadRemoteExhibitions(){
    const jobs=[
      this.client.from("collab_venues").select("*").order("name"),
      this.client.from("collab_exhibitions").select("*").order("title"),
      this.client.from("collab_exhibition_schedule").select("*").order("starts_on"),
      this.client.from("collab_agenda_events").select("*").order("starts_at"),
      this.client.from("collab_event_participants").select("*").order("responded_at",{ascending:false}),
      this.client.from("collab_exhibition_logistics_checklist").select("*").order("sort_order").order("due_at")
    ];
    const[venues,exhibitions,schedules,events,participants,checklist]=await Promise.all(jobs);
    const error=[venues,exhibitions,schedules,events,participants,checklist].find(item=>item.error)?.error;
    if(error){this.state.error=error.message;return;}
    this.state.exhibitionWorkspace={
      venues:venues.data||[],
      exhibitions:exhibitions.data||[],
      schedules:schedules.data||[],
      events:events.data||[],
      participants:participants.data||[],
      checklist:checklist.data||[],
      conflicts:[]
    };
    this.state.exhibitions=this.state.exhibitionWorkspace.schedules;
  }

  loadDemoContext(){const stored=localStorage.getItem(DEMO_KEY);if(stored){try{this.applyDemoContext(JSON.parse(stored));return;}catch{localStorage.removeItem(DEMO_KEY);}}}
  applyDemoContext(demo){
    const roleCodes=demo.roles||[],permissions=expandRolePermissions(roleCodes,this.foundation.rolePermissions,this.foundation.permissions);
    this.state.authenticated=true;this.state.session={user:{id:demo.userId,email:demo.email,user_metadata:{full_name:demo.displayName}}};this.state.profile={user_id:demo.userId,email:demo.email,display_name:demo.displayName,avatar_url:null,primary_profile_type:demo.primaryProfileType||null,locale:"pt-PT",bio:demo.bio||"",phone:"",organization_name:demo.organizationName||"",languages:demo.languages||["pt-PT"],interests:demo.interests||[],skills:demo.skills||[],public_recognition_opt_in:false};
    this.state.membership={status:demo.status||"pending",primary_profile_type:demo.primaryProfileType||null};this.state.accessRequest=demo.accessRequest||null;this.state.roles=roleCodes;this.state.permissions=permissions;this.state.modules=visibleModules(this.state,this.foundation.modules);this.state.taskWorkspace=demo.taskWorkspace||emptyTaskWorkspace();this.state.tasks=this.state.taskWorkspace.tasks;this.state.exhibitionWorkspace=demo.exhibitionWorkspace||emptyExhibitionWorkspace();this.state.exhibitions=this.state.exhibitionWorkspace.schedules;this.state.management=demo.management||emptyManagement();this.state.notice="Modo de demonstração local — não utiliza contas, membros ou dados reais.";
  }
  persistDemo(partial){const current=this.state.session?.user?{userId:this.state.session.user.id,email:this.state.session.user.email,displayName:this.state.profile?.display_name||"",primaryProfileType:this.state.profile?.primary_profile_type||null,status:this.state.membership?.status||"pending",roles:this.state.roles,accessRequest:this.state.accessRequest,bio:this.state.profile?.bio||"",organizationName:this.state.profile?.organization_name||"",languages:this.state.profile?.languages||["pt-PT"],interests:this.state.profile?.interests||[],skills:this.state.profile?.skills||[],taskWorkspace:this.state.taskWorkspace,exhibitionWorkspace:this.state.exhibitionWorkspace,management:this.state.management}:{};const next={...current,...partial};localStorage.setItem(DEMO_KEY,JSON.stringify(next));this.applyDemoContext(next);this.emit();}

  async signInGoogle(){if(this.config.mode!=="supabase"||!this.client)throw new Error("Configure o Supabase e o Google OAuth para utilizar este botão.");const{error}=await this.client.auth.signInWithOAuth({provider:this.config.googleProvider||"google",options:{redirectTo:callbackUrl(this.config),scopes:"openid email profile"}});if(error)throw error;}

  demoSignIn(kind="pending"){
    if(!this.config.allowDemo)throw new Error("Modo de demonstração desativado.");const master=kind==="master",volunteer=kind==="volunteer",now=new Date().toISOString();
    const members=[{user_id:"demo-master",email:"demo.master@local.invalid",display_name:"Master de demonstração",primary_profile_type:"coordinator",organization_name:"Projeto Comunitário de Milreu",languages:["pt-PT"],membership:{status:"active",approved_at:now},roles:["master"],interests:["museum-memories","events"],skills:["cataloguing"]},{user_id:"demo-volunteer",email:"voluntario@local.invalid",display_name:"Voluntário de demonstração",primary_profile_type:"volunteer",languages:["pt-PT"],membership:{status:"active",approved_at:now},roles:["volunteer"],interests:["photography","events"],skills:["digitisation","event-support","transcription"]},{user_id:"demo-request",email:"pedido@local.invalid",display_name:"Pedido de demonstração",primary_profile_type:"volunteer",languages:["pt-PT"],membership:{status:"pending",requested_at:now},roles:[],interests:[],skills:[]},{user_id:"demo-suspended",email:"investigador@local.invalid",display_name:"Investigador suspenso",primary_profile_type:"researcher",languages:["pt-PT","en"],membership:{status:"suspended",suspended_at:now},roles:["researcher"],interests:["research"],skills:["historical-research"]}];
    const management=master?{members,requests:[{id:"demo-request-id",user_id:"demo-request",requested_profile_type:"volunteer",motivation:"Quero apoiar a recolha e digitalização de fotografias.",status:"pending",submitted_at:now}],invitations:[{id:"demo-invite",email:"convidado@local.invalid",intended_profile_type:"reviewer",role_codes:["reviewer"],status:"pending",created_at:now,expires_at:null}],notes:[],audit:[demoAudit("system.master_bootstrapped","demo-master"),demoAudit("membership.suspended","demo-suspended")]}:emptyManagement();
    const workspace=createDemoTaskWorkspace();const exhibitionWorkspace=createDemoExhibitionWorkspace();
    if(volunteer){workspace.tasks=workspace.tasks.filter(task=>task.status!=="draft");workspace.requiredSkills=workspace.requiredSkills.filter(item=>workspace.tasks.some(task=>task.id===item.task_id));workspace.updates=workspace.updates.filter(item=>workspace.tasks.some(task=>task.id===item.task_id));}
    const demo={userId:master?"demo-master":volunteer?"demo-volunteer":"demo-pending",email:master?"demo.master@local.invalid":volunteer?"voluntario@local.invalid":"demo.user@local.invalid",displayName:master?"Master de demonstração":volunteer?"Voluntário de demonstração":"Utilizador de demonstração",primaryProfileType:master?"coordinator":volunteer?"volunteer":null,status:(master||volunteer)?"active":"pending",roles:master?["master"]:volunteer?["volunteer"]:[],accessRequest:(master||volunteer)?{status:"approved"}:null,taskWorkspace:workspace,exhibitionWorkspace,management,languages:["pt-PT"],interests:master?["museum-memories","events"]:volunteer?["photography","events"]:[],skills:master?["cataloguing"]:volunteer?["digitisation","event-support","transcription"]:[]};
    localStorage.setItem(DEMO_KEY,JSON.stringify(demo));this.applyDemoContext(demo);this.emit();
  }

  async submitAccessRequest({displayName,primaryProfileType,motivation}){if(!displayName?.trim()||!primaryProfileType)throw new Error("Nome e perfil principal são obrigatórios.");if(this.config.mode==="demo"){this.persistDemo({displayName:displayName.trim(),primaryProfileType,status:"pending",accessRequest:{status:"pending",requested_profile_type:primaryProfileType,motivation:motivation||""}});return;}const{error}=await this.client.rpc("collab_submit_access_request",{p_display_name:displayName.trim(),p_primary_profile_type:primaryProfileType,p_motivation:motivation||null});if(error)throw error;const{data:s}=await this.client.auth.getSession();await this.loadRemoteContext(s.session);this.emit();}

  async updateMyProfile(values){const interests=values.interests||[],skills=values.skills||[],languages=values.languages?.length?values.languages:["pt-PT"];if(this.config.mode==="demo"){this.persistDemo({displayName:values.displayName?.trim()||this.state.profile.display_name,primaryProfileType:values.primaryProfileType||this.state.profile.primary_profile_type,bio:values.bio||"",organizationName:values.organizationName||"",languages,interests,skills});return;}const{error}=await this.client.rpc("collab_update_my_profile_08b",{p_display_name:values.displayName,p_primary_profile_type:values.primaryProfileType||null,p_locale:values.locale||"pt-PT",p_bio:values.bio||null,p_phone:values.phone||null,p_public_recognition_opt_in:Boolean(values.publicRecognitionOptIn),p_organization_name:values.organizationName||null,p_languages:languages,p_interests:interests,p_skills:skills});if(error)throw error;const{data:s}=await this.client.auth.getSession();await this.loadRemoteContext(s.session);this.emit();}

  async manageMember(values){if(!hasPermission(this.state,"memberships.manage"))throw new Error("Permissão insuficiente.");const roleCodes=values.roleCodes||[];if(this.config.mode==="demo"){const management=structuredClone(this.state.management),member=management.members.find(x=>x.user_id===values.userId);if(!member)throw new Error("Membro não encontrado.");const currentMasters=management.members.filter(x=>x.membership?.status==="active"&&x.roles?.includes("master"));if(member.roles?.includes("master")&&(!roleCodes.includes("master")||values.status!=="active")&&currentMasters.length<=1)throw new Error("O último master ativo não pode ser removido ou suspenso.");member.primary_profile_type=values.primaryProfileType;member.membership={...member.membership,status:values.status,primary_profile_type:values.primaryProfileType,notes:values.note||member.membership?.notes};member.roles=roleCodes;const request=management.requests.find(x=>x.user_id===values.userId&&x.status==="pending");if(request&&values.status==="active")request.status="approved";if(request&&values.status==="rejected")request.status="rejected";if(values.note)management.notes.unshift({id:`demo-note-${Date.now()}`,user_id:values.userId,note:values.note,created_by:this.state.session.user.id,created_at:new Date().toISOString()});management.audit.unshift(demoAudit("membership.managed",values.userId,this.state.session.user.id,{status:values.status,roles:roleCodes}));this.persistDemo({management});return;}const{error}=await this.client.rpc("collab_manage_member",{p_user_id:values.userId,p_primary_profile_type:values.primaryProfileType,p_role_codes:roleCodes,p_status:values.status,p_note:values.note||null});if(error)throw error;await this.loadRemoteManagement();this.emit();}

  async createInvitation(values){if(!hasPermission(this.state,"invitations.manage"))throw new Error("Permissão insuficiente.");if(this.config.mode==="demo"){const management=structuredClone(this.state.management);management.invitations.unshift({id:`demo-invite-${Date.now()}`,email:values.email.toLowerCase(),intended_profile_type:values.primaryProfileType,role_codes:values.roleCodes||["volunteer"],status:"pending",created_at:new Date().toISOString(),expires_at:values.expiresAt||null,internal_notes:values.notes||null});management.audit.unshift(demoAudit("invitation.created",values.email,this.state.session.user.id));this.persistDemo({management});return;}const{error}=await this.client.rpc("collab_create_access_invitation",{p_email:values.email,p_profile_type:values.primaryProfileType,p_role_codes:values.roleCodes||["volunteer"],p_expires_at:values.expiresAt||null,p_notes:values.notes||null});if(error)throw error;await this.loadRemoteManagement();this.emit();}
  async revokeInvitation(invitationId,reason=""){if(this.config.mode==="demo"){const management=structuredClone(this.state.management),inv=management.invitations.find(x=>x.id===invitationId);if(inv){inv.status="revoked";inv.revoked_at=new Date().toISOString();}management.audit.unshift(demoAudit("invitation.revoked",invitationId,this.state.session.user.id));this.persistDemo({management});return;}const{error}=await this.client.rpc("collab_revoke_access_invitation",{p_invitation_id:invitationId,p_reason:reason||null});if(error)throw error;await this.loadRemoteManagement();this.emit();}

  demoWorkspaceUpdate(mutator){const taskWorkspace=structuredClone(this.state.taskWorkspace);mutator(taskWorkspace);this.persistDemo({taskWorkspace});}
  addDemoTaskUpdate(workspace,taskId,type,note="",userId=this.state.session.user.id,metadata={}){workspace.updates.unshift(demoTaskUpdate(taskId,userId,type,note,metadata));}
  async refreshTasks(){if(this.config.mode==="supabase"){await this.loadRemoteTasks();this.emit();}}

  async saveAvailability(values){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{workspace.preferences={project_id:"demo-project",user_id:this.state.session.user.id,preferred_modes:values.preferredModes,maximum_weekly_minutes:values.maximumWeeklyMinutes,availability_notes:values.notes,timezone:values.timezone};workspace.availability=values.slots.map((slot,index)=>({id:`demo-slot-${Date.now()}-${index}`,project_id:"demo-project",user_id:this.state.session.user.id,day_of_week:Number(slot.dayOfWeek),starts_at:`${slot.startsAt}:00`,ends_at:`${slot.endsAt}:00`,mode:slot.mode,active:true}));});return;}const{error}=await this.client.rpc("collab_set_my_availability_08c",{p_preferences:{preferredModes:values.preferredModes,maximumWeeklyMinutes:values.maximumWeeklyMinutes,notes:values.notes||null,timezone:values.timezone||"Europe/Lisbon"},p_slots:values.slots});if(error)throw error;await this.refreshTasks();}

  async createTask(payload){if(this.config.mode==="demo"){const id=`demo-task-${Date.now()}`;this.demoWorkspaceUpdate(workspace=>{workspace.tasks.unshift({id,project_id:"demo-project",title:payload.title,summary:payload.summary||null,description:payload.description||null,instructions:payload.instructions||null,category:payload.categoryCode,category_code:payload.categoryCode,status:"draft",priority:payload.priority||"normal",assignment_mode:payload.assignmentMode||"approval",location_mode:payload.locationMode||"flexible",location_name:payload.locationName||null,municipality:payload.municipality||null,starts_at:payload.startsAt||null,due_at:payload.dueAt||null,application_deadline:payload.applicationDeadline||null,estimated_minutes:payload.estimatedMinutes||null,capacity:payload.capacity||null,minimum_participants:payload.minimumParticipants||1,visibility:"members",recognition_eligible:Boolean(payload.recognitionEligible),created_by:this.state.session.user.id,updated_at:new Date().toISOString()});for(const skill of payload.skills||[])workspace.requiredSkills.push({task_id:id,skill_code:skill.code,required:Boolean(skill.required)});this.addDemoTaskUpdate(workspace,id,"progress","Rascunho criado.");});return id;}const{data,error}=await this.client.rpc("collab_create_task_08c",{p_payload:payload});if(error)throw error;await this.refreshTasks();return data;}
  async updateTask(taskId,payload){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const task=workspace.tasks.find(x=>x.id===taskId);if(!task)throw new Error("Tarefa não encontrada.");Object.assign(task,{title:payload.title||task.title,summary:payload.summary??task.summary,description:payload.description??task.description,instructions:payload.instructions??task.instructions,category:payload.categoryCode||task.category,category_code:payload.categoryCode||task.category_code,priority:payload.priority||task.priority,assignment_mode:payload.assignmentMode||task.assignment_mode,location_mode:payload.locationMode||task.location_mode,location_name:payload.locationName??task.location_name,municipality:payload.municipality??task.municipality,starts_at:payload.startsAt??task.starts_at,due_at:payload.dueAt??task.due_at,application_deadline:payload.applicationDeadline??task.application_deadline,estimated_minutes:payload.estimatedMinutes??task.estimated_minutes,capacity:payload.capacity??task.capacity,minimum_participants:payload.minimumParticipants??task.minimum_participants,recognition_eligible:Boolean(payload.recognitionEligible),updated_at:new Date().toISOString()});workspace.requiredSkills=workspace.requiredSkills.filter(x=>x.task_id!==taskId);for(const skill of payload.skills||[])workspace.requiredSkills.push({task_id:taskId,skill_code:skill.code,required:Boolean(skill.required)});this.addDemoTaskUpdate(workspace,taskId,"progress","Tarefa atualizada.");});return;}const{error}=await this.client.rpc("collab_update_task_08c",{p_task_id:taskId,p_payload:payload});if(error)throw error;await this.refreshTasks();}
  async publishTask(taskId){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const task=workspace.tasks.find(x=>x.id===taskId);if(!task||task.status!=="draft")throw new Error("Tarefa não publicável.");task.status="open";this.addDemoTaskUpdate(workspace,taskId,"progress","Tarefa publicada.");});return;}const{error}=await this.client.rpc("collab_publish_task_08c",{p_task_id:taskId});if(error)throw error;await this.refreshTasks();}
  async cancelTask(taskId,reason=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const task=workspace.tasks.find(x=>x.id===taskId);if(!task)throw new Error("Tarefa não encontrada.");task.status="cancelled";workspace.assignments.filter(x=>x.task_id===taskId&&!['completed','declined','withdrawn'].includes(x.status)).forEach(x=>x.status="cancelled");this.addDemoTaskUpdate(workspace,taskId,"cancelled",reason);});return;}const{error}=await this.client.rpc("collab_cancel_task_08c",{p_task_id:taskId,p_reason:reason||null});if(error)throw error;await this.refreshTasks();}
  async completeTask(taskId,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const task=workspace.tasks.find(x=>x.id===taskId);if(!task)throw new Error("Tarefa não encontrada.");if(workspace.assignments.some(x=>x.task_id===taskId&&['accepted','in-progress','submitted'].includes(x.status)))throw new Error("Ainda existem participações abertas.");task.status="completed";workspace.assignments.filter(x=>x.task_id===taskId&&["invited","applied"].includes(x.status)).forEach(x=>x.status="cancelled");this.addDemoTaskUpdate(workspace,taskId,"verified",note);});return;}const{error}=await this.client.rpc("collab_complete_task_08c",{p_task_id:taskId,p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async joinTask(taskId,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const task=workspace.tasks.find(x=>x.id===taskId);if(!task||task.status!=="open")throw new Error("Tarefa indisponível.");const existing=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===this.state.session.user.id);if(existing&&!['declined','withdrawn','cancelled'].includes(existing.status))throw new Error("Já existe uma participação.");const status=task.assignment_mode==="open"?"accepted":"applied",row={task_id:taskId,user_id:this.state.session.user.id,status,applied_at:new Date().toISOString(),accepted_at:status==="accepted"?new Date().toISOString():null,application_note:note,updated_at:new Date().toISOString()};if(existing)Object.assign(existing,row);else workspace.assignments.push(row);this.addDemoTaskUpdate(workspace,taskId,status==="accepted"?"accepted":"application",note);});return;}const{error}=await this.client.rpc("collab_join_task_08c",{p_task_id:taskId,p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async inviteTaskMember(taskId,userId,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{let assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===userId);const row={task_id:taskId,user_id:userId,status:"invited",assigned_by:this.state.session.user.id,assigned_at:new Date().toISOString(),manager_note:note,updated_at:new Date().toISOString()};if(assignment)Object.assign(assignment,row);else workspace.assignments.push(row);this.addDemoTaskUpdate(workspace,taskId,"invitation",note,userId);});return;}const{error}=await this.client.rpc("collab_invite_task_member_08c",{p_task_id:taskId,p_user_id:userId,p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async respondTaskInvitation(taskId,accept,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===this.state.session.user.id&&x.status==="invited");if(!assignment)throw new Error("Convite não encontrado.");assignment.status=accept?"accepted":"declined";assignment.accepted_at=accept?new Date().toISOString():null;assignment.declined_at=!accept?new Date().toISOString():null;this.addDemoTaskUpdate(workspace,taskId,accept?"accepted":"declined",note);});return;}const{error}=await this.client.rpc("collab_respond_task_invitation_08c",{p_task_id:taskId,p_accept:Boolean(accept),p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async reviewTaskApplication(taskId,userId,accept,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===userId&&x.status==="applied");if(!assignment)throw new Error("Candidatura não encontrada.");assignment.status=accept?"accepted":"declined";assignment.manager_note=note;assignment.accepted_at=accept?new Date().toISOString():null;this.addDemoTaskUpdate(workspace,taskId,accept?"accepted":"declined",note,userId);});return;}const{error}=await this.client.rpc("collab_review_task_application_08c",{p_task_id:taskId,p_user_id:userId,p_accept:Boolean(accept),p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async startTask(taskId){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===this.state.session.user.id&&x.status==="accepted");if(!assignment)throw new Error("Tarefa não pode ser iniciada.");assignment.status="in-progress";assignment.started_at=new Date().toISOString();const task=workspace.tasks.find(x=>x.id===taskId);if(task?.status==="open")task.status="in-progress";this.addDemoTaskUpdate(workspace,taskId,"started");});return;}const{error}=await this.client.rpc("collab_start_task_08c",{p_task_id:taskId});if(error)throw error;await this.refreshTasks();}
  async submitTask(taskId,note="",minutes=null){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===this.state.session.user.id&&['accepted','in-progress'].includes(x.status));if(!assignment)throw new Error("Tarefa não pode ser submetida.");assignment.status="submitted";assignment.submitted_at=new Date().toISOString();assignment.completion_note=note;if(minutes)workspace.timeEntries.unshift({id:`demo-time-${Date.now()}`,project_id:"demo-project",task_id:taskId,user_id:this.state.session.user.id,activity_date:new Date().toISOString().slice(0,10),minutes:Number(minutes),note,status:"pending",created_at:new Date().toISOString()});this.addDemoTaskUpdate(workspace,taskId,"submitted",note,{minutes});});return;}const{error}=await this.client.rpc("collab_submit_task_08c",{p_task_id:taskId,p_note:note||null,p_minutes:minutes?Number(minutes):null});if(error)throw error;await this.refreshTasks();}
  async verifyTask(taskId,userId,accept,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===userId&&x.status==="submitted");if(!assignment)throw new Error("Submissão não encontrada.");assignment.status=accept?"completed":"in-progress";assignment.manager_note=note;assignment.verified_at=accept?new Date().toISOString():null;workspace.timeEntries.filter(x=>x.task_id===taskId&&x.user_id===userId&&x.status==="pending").forEach(x=>x.status=accept?"approved":"rejected");this.addDemoTaskUpdate(workspace,taskId,accept?"verified":"reopened",note,userId);});return;}const{error}=await this.client.rpc("collab_verify_task_08c",{p_task_id:taskId,p_user_id:userId,p_accept:Boolean(accept),p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async withdrawTask(taskId,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{const assignment=workspace.assignments.find(x=>x.task_id===taskId&&x.user_id===this.state.session.user.id&&!['completed','withdrawn','cancelled'].includes(x.status));if(!assignment)throw new Error("Participação não pode ser retirada.");assignment.status="withdrawn";assignment.withdrawn_at=new Date().toISOString();assignment.completion_note=note;this.addDemoTaskUpdate(workspace,taskId,"withdrawn",note);});return;}const{error}=await this.client.rpc("collab_withdraw_task_08c",{p_task_id:taskId,p_note:note||null});if(error)throw error;await this.refreshTasks();}
  async logTaskTime(taskId,activityDate,minutes,note=""){if(this.config.mode==="demo"){this.demoWorkspaceUpdate(workspace=>{workspace.timeEntries.unshift({id:`demo-time-${Date.now()}`,project_id:"demo-project",task_id:taskId,user_id:this.state.session.user.id,activity_date:activityDate,minutes:Number(minutes),note,status:"pending",created_at:new Date().toISOString()});this.addDemoTaskUpdate(workspace,taskId,"time-log",note,{minutes:Number(minutes)});});return;}const{error}=await this.client.rpc("collab_log_task_time_08c",{p_task_id:taskId,p_activity_date:activityDate,p_minutes:Number(minutes),p_note:note||null});if(error)throw error;await this.refreshTasks();}


  demoExhibitionUpdate(mutator){const exhibitionWorkspace=structuredClone(this.state.exhibitionWorkspace);mutator(exhibitionWorkspace);this.persistDemo({exhibitionWorkspace});}
  async refreshExhibitions(){if(this.config.mode==="supabase"){await this.loadRemoteExhibitions();this.emit();}}

  async saveVenue(venueId,payload){
    if(!hasPermission(this.state,"venues.manage"))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{const id=venueId||`demo-venue-${Date.now()}`;let row=workspace.venues.find(item=>item.id===id);const next={id,project_id:"demo-project",...payload,name:payload.name?.trim(),venue_type:payload.venueType||"other",address_text:payload.addressText||null,country_code:payload.countryCode||"PT",postal_code:payload.postalCode||null,contact_name:payload.contactName||null,contact_email:payload.contactEmail||null,public_email:payload.publicEmail||null,public_phone:payload.publicPhone||null,public_url:payload.publicUrl||null,opening_hours:payload.openingHours||null,public_description:payload.publicDescription||null,accessibility_notes:payload.accessibilityNotes||null,accessibility_summary:payload.accessibilitySummary||null,internal_notes:payload.internalNotes||null,public_visibility:Boolean(payload.publicVisibility),active:payload.status!=="archived",updated_at:new Date().toISOString()};if(!next.name)throw new Error("Nome do local é obrigatório.");if(row)Object.assign(row,next);else workspace.venues.push(next);});return;}
    const{error}=await this.client.rpc("collab_upsert_venue_08d",{p_venue_id:venueId||null,p_payload:payload});if(error)throw error;await this.refreshExhibitions();
  }

  async saveExhibition(exhibitionId,payload){
    if(!hasPermission(this.state,"exhibitions.manage"))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{const id=exhibitionId||`demo-exhibition-${Date.now()}`;let row=workspace.exhibitions.find(item=>item.id===id);const next={id,project_id:"demo-project",...payload,title:payload.title?.trim(),exhibition_type:payload.exhibitionType||"itinerant",public_summary:payload.publicSummary||null,internal_objectives:payload.internalObjectives||null,default_duration_days:payload.defaultDurationDays?Number(payload.defaultDurationDays):null,public_visibility:Boolean(payload.publicVisibility),published_at:payload.publicVisibility&&payload.publishNow?(row?.published_at||new Date().toISOString()):row?.published_at||null,updated_at:new Date().toISOString()};if(!next.title)throw new Error("Título da exposição é obrigatório.");if(row)Object.assign(row,next);else workspace.exhibitions.push(next);});return;}
    const{error}=await this.client.rpc("collab_upsert_exhibition_08d",{p_exhibition_id:exhibitionId||null,p_payload:payload});if(error)throw error;await this.refreshExhibitions();
  }

  async checkScheduleConflicts(scheduleId,payload){
    if(this.config.mode==="demo"){
      const workspace=this.state.exhibitionWorkspace;
      const overlap=(row)=>row.id!==scheduleId&&row.status!=="cancelled"&&row.starts_on<=payload.endsOn&&row.ends_on>=payload.startsOn;
      return{
        exhibitionOverlaps:workspace.schedules.filter(row=>row.exhibition_id===payload.exhibitionId&&overlap(row)),
        venueWarnings:workspace.schedules.filter(row=>row.venue_id===payload.venueId&&overlap(row))
      };
    }
    const{data,error}=await this.client.rpc("collab_schedule_conflicts_08d",{p_schedule_id:scheduleId||null,p_exhibition_id:payload.exhibitionId,p_venue_id:payload.venueId,p_starts_on:payload.startsOn,p_ends_on:payload.endsOn});if(error)throw error;return data;
  }

  async saveSchedule(scheduleId,payload){
    if(!hasPermission(this.state,"exhibitions.manage"))throw new Error("Permissão insuficiente.");
    const conflicts=await this.checkScheduleConflicts(scheduleId,payload);
    if(conflicts.exhibitionOverlaps?.length)throw new Error("A exposição já possui outro período que se sobrepõe.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{const id=scheduleId||`demo-schedule-${Date.now()}`;let row=workspace.schedules.find(item=>item.id===id);const next={id,project_id:"demo-project",...payload,exhibition_id:payload.exhibitionId,venue_id:payload.venueId,starts_on:payload.startsOn,ends_on:payload.endsOn,installation_at:payload.installationAt||null,dismantling_at:payload.dismantlingAt||null,public_title:payload.publicTitle||null,public_summary:payload.publicSummary||null,public_notes:payload.publicNotes||null,internal_notes:payload.internalNotes||null,public_visibility:Boolean(payload.publicVisibility),published_at:payload.publicVisibility&&payload.publishNow?(row?.published_at||new Date().toISOString()):row?.published_at||null,opening_hours:payload.openingHours||null,public_contact:payload.publicContact||null,registration_url:payload.registrationUrl||null,installation_status:payload.installationStatus||"not-started",logistics_status:payload.logisticsStatus||"not-started",transport_notes:payload.transportNotes||null,condition_report_before:payload.conditionReportBefore||null,condition_report_after:payload.conditionReportAfter||null,updated_at:new Date().toISOString()};if(row)Object.assign(row,next);else workspace.schedules.push(next);workspace.conflicts=conflicts.venueWarnings||[];});return conflicts;}
    const{data,error}=await this.client.rpc("collab_upsert_schedule_08d",{p_schedule_id:scheduleId||null,p_payload:payload});if(error)throw error;await this.refreshExhibitions();return data?.conflicts||conflicts;
  }

  async saveAgendaEvent(eventId,payload){
    if(!hasPermission(this.state,"agenda.manage"))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{const id=eventId||`demo-event-${Date.now()}`;let row=workspace.events.find(item=>item.id===id);const next={id,project_id:"demo-project",...payload,exhibition_schedule_id:payload.exhibitionScheduleId||null,task_id:payload.taskId||null,venue_id:payload.venueId||null,event_type:payload.eventType||"other",starts_at:payload.startsAt,ends_at:payload.endsAt,location_text:payload.locationText||null,registration_required:Boolean(payload.registrationRequired),registration_url:payload.registrationUrl||null,public_contact:payload.publicContact||null,updated_at:new Date().toISOString()};if(!next.title?.trim())throw new Error("Título do evento é obrigatório.");if(row)Object.assign(row,next);else workspace.events.push(next);});return;}
    const{error}=await this.client.rpc("collab_upsert_agenda_event_08d",{p_event_id:eventId||null,p_payload:payload});if(error)throw error;await this.refreshExhibitions();
  }

  async rsvpEvent(eventId,status,notes=""){
    if(!hasPermission(this.state,"agenda.rsvp"))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{let row=workspace.participants.find(item=>item.event_id===eventId&&item.user_id===this.state.session.user.id);const event=workspace.events.find(item=>item.id===eventId);if(!event||event.status!=="confirmed")throw new Error("Evento indisponível.");let nextStatus=status;if(status==="attending"&&event.capacity){const count=workspace.participants.filter(item=>item.event_id===eventId&&["attending","attended"].includes(item.status)&&item.user_id!==this.state.session.user.id).length;if(count>=event.capacity)nextStatus="waitlist";}const next={event_id:eventId,user_id:this.state.session.user.id,status:nextStatus,notes,responded_at:new Date().toISOString()};if(row)Object.assign(row,next);else workspace.participants.push(next);});return;}
    const{error}=await this.client.rpc("collab_rsvp_event_08d",{p_event_id:eventId,p_status:status,p_notes:notes||null});if(error)throw error;await this.refreshExhibitions();
  }

  async saveChecklistItem(itemId,scheduleId,payload){
    if(!(hasPermission(this.state,"exhibitions.logistics")||hasPermission(this.state,"exhibitions.manage")))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{const id=itemId||`demo-check-${Date.now()}`;let row=workspace.checklist.find(item=>item.id===id);const next={id,project_id:"demo-project",schedule_id:scheduleId,...payload,assigned_to:payload.assignedTo||null,due_at:payload.dueAt||null,sort_order:Number(payload.sortOrder||0),completed_at:payload.status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString()};if(!next.title?.trim())throw new Error("Título do item é obrigatório.");if(row)Object.assign(row,next);else workspace.checklist.push(next);});return;}
    const{error}=await this.client.rpc("collab_upsert_checklist_item_08d",{p_item_id:itemId||null,p_schedule_id:scheduleId,p_payload:payload});if(error)throw error;await this.refreshExhibitions();
  }

  async publishSchedule(scheduleId,publish){
    if(!hasPermission(this.state,"exhibitions.publish"))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){this.demoExhibitionUpdate(workspace=>{const row=workspace.schedules.find(item=>item.id===scheduleId);if(!row||!["confirmed","installed","open","closed"].includes(row.status))throw new Error("Período ainda não publicável.");row.public_visibility=Boolean(publish);row.published_at=publish?(row.published_at||new Date().toISOString()):null;});return;}
    const{error}=await this.client.rpc("collab_publish_schedule_08d",{p_schedule_id:scheduleId,p_publish:Boolean(publish)});if(error)throw error;await this.refreshExhibitions();
  }

  async generateLogisticsTasks(scheduleId){
    if(!(hasPermission(this.state,"exhibitions.logistics")&&hasPermission(this.state,"tasks.manage")))throw new Error("Permissão insuficiente.");
    if(this.config.mode==="demo"){const workspace=structuredClone(this.state.taskWorkspace),exhibitions=this.state.exhibitionWorkspace,schedule=exhibitions.schedules.find(item=>item.id===scheduleId),exhibition=exhibitions.exhibitions.find(item=>item.id===schedule?.exhibition_id),venue=exhibitions.venues.find(item=>item.id===schedule?.venue_id);if(!schedule)throw new Error("Agendamento não encontrado.");for(const type of ["Montagem","Desmontagem"]){const title=`${type} — ${exhibition?.title||"Exposição"}`;if(!workspace.tasks.some(item=>item.source_entity_id===scheduleId&&item.title===title))workspace.tasks.push({id:`demo-task-logistics-${type}-${Date.now()}`,project_id:"demo-project",title,summary:`${type} em ${venue?.name||"local por definir"}.`,description:"Tarefa gerada pela gestão da exposição.",category:"exhibition-setup",category_code:"exhibition-setup",status:"draft",priority:"high",assignment_mode:"approval",location_mode:"on-site",location_name:venue?.name||null,starts_at:type==="Montagem"?schedule.installation_at:schedule.dismantling_at,due_at:type==="Montagem"?schedule.installation_at:schedule.dismantling_at,estimated_minutes:180,source_entity_type:"exhibition_schedule",source_entity_id:scheduleId,created_by:this.state.session.user.id,updated_at:new Date().toISOString()});}this.persistDemo({taskWorkspace:workspace});return;}
    const{error}=await this.client.rpc("collab_generate_logistics_tasks_08d",{p_schedule_id:scheduleId});if(error)throw error;await Promise.all([this.refreshTasks(),this.refreshExhibitions()]);
  }

  async approveAccess(userId,roleCodes=["volunteer"],notes=""){const member=this.state.management.members.find(x=>x.user_id===userId);return this.manageMember({userId,primaryProfileType:member?.primary_profile_type||"volunteer",roleCodes,status:"active",note:notes});}
  async signOut(){if(this.config.mode==="demo"){localStorage.removeItem(DEMO_KEY);this.resetAuthentication();this.emit();return;}const{error}=await this.client.auth.signOut();if(error)throw error;this.resetAuthentication();this.emit();}
}
export const collaborative=new CollaborativeController();
