/**
 * © 2026 Fernando Rodrigues de Jácomo.
 * Produzido no âmbito do Projeto Comunitário de Milreu.
 * Direitos: consultar RIGHTS.md.
 */

window.MilreuRenderers = (() => {
  const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));
  const statusLabel = status => ({"proposed":"Proposto","draft":"Rascunho","in-review":"Em revisão","validated":"Validado","approved":"Aprovado","deprecated":"Depreciado"}[status] || status);
  const sectionTitle = (id,title) => `<h2 id="${escapeHtml(id)}">${escapeHtml(title)}</h2>`;
  function renderRules(rules){ return `<div class="rule-cards"><article class="rule-card" data-kind="do"><h3>${MilreuI18n.t("do")}</h3><ul>${rules.do.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></article><article class="rule-card" data-kind="avoid"><h3>${MilreuI18n.t("avoid")}</h3><ul>${rules.avoid.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></article></div>`; }
  function renderTokens(tokens){ return `<table class="token-table"><thead><tr><th>Token</th><th>Valor</th><th>Uso</th></tr></thead><tbody>${tokens.map(row=>`<tr><td><code>${escapeHtml(row[0])}</code></td><td>${escapeHtml(row[1])}</td><td>${escapeHtml(row[2])}</td></tr>`).join("")}</tbody></table>`; }
  function renderSection(section){ let html=`<section class="page-section">${sectionTitle(section.id,section.title)}`; if(section.body) html+=section.body.map(p=>`<p>${escapeHtml(p)}</p>`).join(""); if(section.list) html+=`<ul>${section.list.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`; if(section.rules) html+=renderRules(section.rules); if(section.tokens) html+=renderTokens(section.tokens); return html+`</section>`; }
  function renderPreview(type){
    const specialized=window.MilreuComponentRenderers?.preview(type); if(specialized) return specialized;
    const label=`<span class="preview-label">${MilreuI18n.t("previewLabel")}</span>`;
    if(type==="colors") return `<div class="preview-frame">${label}<div class="color-grid">${[["Assinatura","#A83227"],["Profundo","#7E251C"],["Preto aquecido","#1E1A17"],["Leitura","#FFFFFF"],["Canvas","#FFFCF7"],["Linho","#F7F1E7"],["Pátina","#5E7267"],["Sépia","#8A6A4A"]].map(([n,c])=>`<div class="color-card" style="background:${c}"><span>${n}<br><code>${c}</code></span></div>`).join("")}</div></div>`;
    if(type==="typography") return `<div class="preview-frame">${label}<div class="type-specimen"><div class="type-row"><small>Display · Fraunces</small><p class="type-display">Entre <em>Ruínas</em> e Memórias</p></div><div class="type-row"><small>Editorial · Spectral</small><p class="type-editorial">As memórias revelam relações construídas entre pessoas, comunidade, paisagem e Milreu.</p></div><div class="type-row"><small>Interface · Archivo</small><p class="type-interface">MM202601 · Proveniência · Certa</p></div></div></div>`;
    if(type==="spacing") return `<div class="preview-frame">${label}<div class="spacing-demo">${[["1",4],["2",8],["4",16],["6",24],["8",32],["12",48],["16",64],["24",96]].map(([n,p])=>`<div class="spacing-row"><code>${n}</code><span class="spacing-bar" style="width:${p}px"></span><span>${p}px</span></div>`).join("")}</div></div>`;
    if(type==="grid") return `<div class="preview-frame">${label}<div class="grid-demo">${Array.from({length:12},(_,i)=>`<span>${i+1}</span>`).join("")}</div></div>`;
    if(type==="shape") return `<div class="preview-frame">${label}<div class="shape-demo"><span style="border-radius:var(--ml-radius-xs,.125rem)">XS</span><span style="border-radius:var(--ml-radius-sm,.25rem)">SM</span><span style="border-radius:var(--ml-radius-md,.5rem)">MD</span><span style="border-radius:var(--ml-radius-lg,1rem)">LG</span></div></div>`;
    if(type==="motion") return `<div class="preview-frame">${label}<div class="motion-demo"><span class="motion-sample" style="--duration:var(--ml-duration-fast,120ms)">120ms</span><span class="motion-sample" style="--duration:var(--ml-duration-standard,200ms)">200ms</span><span class="motion-sample" style="--duration:var(--ml-duration-editorial,320ms)">320ms</span></div></div>`;
    if(type==="texture") return `<div class="preview-frame">${label}<div class="texture-demo"><div><strong>Textura abstrata</strong><p>Ritmo de linhas, sem reprodução de uma planta ou mosaico específico.</p></div></div></div>`;
    if(type==="maps") return `<div class="preview-frame">${label}<div class="map-palette">${[["Água","#4D82A8"],["Jardim","#79A34A"],["Coberto","#B9C8CD"],["Via","#D7C88A"],["Muro","#8F3A32"],["Alvenaria","#9A7358"]].map(([n,c])=>`<span class="map-chip" style="background:${c}">${n}</span>`).join("")}</div></div>`;
    if(type==="experiences") return `<div class="preview-frame">${label}<div class="experience-grid"><article class="experience-card"><small>PORTAL</small><h3>Consulta estruturada</h3><p>Navegação previsível, leitura, dados, biblioteca e métodos.</p></article><article class="experience-card experience-card--museum"><small>MUSEU</small><h3>Exploração imersiva</h3><p>Fotografia em escala, relações e detalhes por camadas.</p></article></div></div>`;
    if(type==="voices") return `<div class="preview-frame">${label}<div class="experience-grid"><article class="experience-card"><small>VOZ A</small><h3>Comunidade</h3><p>A memória e a fotografia ocupam a superfície.</p></article><article class="experience-card experience-card--museum"><small>VOZ B</small><h3>Instituição</h3><p>Contexto, proveniência, certeza e direitos formam a moldura.</p></article></div></div>`;
    if(type==="signature") return `<div class="preview-frame" style="padding:0"><div style="min-height:20rem;display:grid;grid-template-columns:1fr 1fr"><div style="background:var(--ml-surface-signature,#a83227);padding:2rem;color:white;display:flex;align-items:end"><div><small>ABERTURA</small><h3 style="font:500 3rem/1 var(--ml-font-display,Georgia,serif);margin:.4rem 0">Milreu</h3></div></div><div style="background:var(--ml-surface-inverse,#1e1a17);padding:2rem;color:white;display:flex;align-items:end"><div><small>DESTAQUE</small><p style="font:1.1rem/1.6 var(--ml-font-editorial,Georgia,serif)">Preenchimento preto, breve e deliberado.</p></div></div></div></div>`;
    if(type==="maturity") return `<div class="preview-frame">${label}<table class="maturity-table"><thead><tr><th>Estado</th><th>Significado</th></tr></thead><tbody>${[["proposed","Ideia registada"],["draft","Exploração"],["in-review","Decisão em revisão"],["validated","Base validada"],["approved","Autorizado para produção"],["deprecated","Em retirada"]].map(([s,d])=>`<tr><td><span class="status-badge" data-status="${s}">${statusLabel(s)}</span></td><td>${d}</td></tr>`).join("")}</tbody></table></div>`;
    if(type==="components") return `<div class="preview-frame">${label}<div class="callout"><p>Estrutura pronta para receber o inventário especializado do Pacote 05D. Nenhum placeholder é considerado componente aprovado.</p></div></div>`;
    if(type==="overview") return `<div class="preview-frame" style="padding:0"><div style="min-height:22rem;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(14rem,.8fr)"><div style="padding:clamp(2rem,6vw,4.5rem);background:var(--ml-surface-signature,#a83227);color:white"><small>PROJETO COMUNITÁRIO DE MILREU</small><h2 style="font:500 clamp(3rem,8vw,6rem)/.88 var(--ml-font-display,Georgia,serif);margin:2rem 0 0">Sistema<br>de Design</h2></div><div style="padding:2rem;background:var(--ml-surface-reading,#fff);display:grid;align-content:end"><p style="font:1.1rem/1.65 var(--ml-font-editorial,Georgia,serif)">Uma linguagem para memória, investigação, participação e património.</p></div></div></div>`;
    return `<div class="preview-frame">${label}<div class="callout"><p>Esta página é documental. O exemplo visual específico será desenvolvido numa release posterior.</p></div></div>`;
  }
  function renderPage(page){
    const html=`<header class="page-header"><p class="page-kicker">${escapeHtml(page.group)}</p><div class="page-title-row"><h1>${escapeHtml(page.title)}</h1><span class="status-badge" data-status="${escapeHtml(page.status)}">${escapeHtml(statusLabel(page.status))}</span></div><p class="page-summary">${escapeHtml(page.summary)}</p><dl class="meta-grid"><div class="meta-item"><dt>${MilreuI18n.t("status")}</dt><dd>${escapeHtml(statusLabel(page.status))}</dd></div><div class="meta-item"><dt>${MilreuI18n.t("source")}</dt><dd>${escapeHtml(page.source)}</dd></div><div class="meta-item"><dt>${MilreuI18n.t("platform")}</dt><dd>${escapeHtml(page.platform)}</dd></div><div class="meta-item"><dt>Tags</dt><dd>${page.tags.map(escapeHtml).join(" · ")}</dd></div></dl></header>${renderPreview(page.preview)}${page.sections.map(renderSection).join("")}${window.MilreuComponentRenderers?.documentation(page)||""}<section class="page-section"><h2 id="implementation">Implementação</h2><p>Esta página é alimentada pelo registo estruturado <code>packages/design-guide-catalog/v0.4/catalog.json</code>.</p><div class="code-block"><button class="copy-button" type="button" data-copy="${escapeHtml(page.id)}">${MilreuI18n.t("copy")}</button><pre><code>#/${escapeHtml(page.id)}</code></pre></div></section>`;
    document.getElementById("page-content").innerHTML=html;
    bindCopyButtons(); window.MilreuComponents?.enhance(document.getElementById('page-content')); window.MilreuPatterns?.enhance(document.getElementById('page-content'));
  }
  function bindCopyButtons(){ document.querySelectorAll("[data-copy]").forEach(button=>button.addEventListener("click",async()=>{ await navigator.clipboard?.writeText(`#/${button.dataset.copy}`); button.textContent=MilreuI18n.t("copied"); setTimeout(()=>button.textContent=MilreuI18n.t("copy"),1200); })); }
  return {renderPage,statusLabel};
})();
