/**
 * © 2026 Fernando Rodrigues de Jácomo.
 * Produzido no âmbito do Projeto Comunitário de Milreu.
 * Consultar RIGHTS.md no repositório principal.
 */
const langs=["pt-PT","en","es","fr"];
let lang=localStorage.getItem("milreu-arch-lang")||"pt-PT";
const T={
"pt-PT":{project:"Projeto",initiatives:"Iniciativas",museum:"Museu",knowledge:"Conhecimento",data:"Dados",library:"Biblioteca",participate:"Participar",explore:"Explorar",timeline:"Linha temporal",collections:"Coleções",back:"Voltar ao Projeto",title:"Projeto Comunitário de Milreu",subtitle:"Memórias, conhecimento e participação em torno de Milreu.",enter:"Entrar no Museu",demo:"PROTÓTIPO — CONTEÚDO DEMONSTRATIVO",fullscreen:"Ecrã inteiro",close:"Fechar",unavailable:"Este registo não está disponível para publicação."},
en:{project:"Project",initiatives:"Initiatives",museum:"Museum",knowledge:"Knowledge",data:"Data",library:"Library",participate:"Participate",explore:"Explore",timeline:"Timeline",collections:"Collections",back:"Back to Project",title:"Milreu Community Project",subtitle:"Memories, knowledge and participation around Milreu.",enter:"Enter the Museum",demo:"PROTOTYPE — DEMONSTRATION CONTENT",fullscreen:"Fullscreen",close:"Close",unavailable:"This record is not available for publication."},
es:{project:"Proyecto",initiatives:"Iniciativas",museum:"Museo",knowledge:"Conocimiento",data:"Datos",library:"Biblioteca",participate:"Participar",explore:"Explorar",timeline:"Cronología",collections:"Colecciones",back:"Volver al Proyecto",title:"Proyecto Comunitario de Milreu",subtitle:"Memorias, conocimiento y participación en torno a Milreu.",enter:"Entrar en el Museo",demo:"PROTOTIPO — CONTENIDO DEMOSTRATIVO",fullscreen:"Pantalla completa",close:"Cerrar",unavailable:"Este registro no está disponible para publicación."},
fr:{project:"Projet",initiatives:"Initiatives",museum:"Musée",knowledge:"Connaissance",data:"Données",library:"Bibliothèque",participate:"Participer",explore:"Explorer",timeline:"Chronologie",collections:"Collections",back:"Retour au Projet",title:"Projet Communautaire de Milreu",subtitle:"Mémoires, connaissances et participation autour de Milreu.",enter:"Entrer dans le Musée",demo:"PROTOTYPE — CONTENU DE DÉMONSTRATION",fullscreen:"Plein écran",close:"Fermer",unavailable:"Cette notice n’est pas disponible à la publication."}
};
const q=k=>T[lang]?.[k]||T["pt-PT"][k]||k;
const memories=[
{id:"DEMO-001",year:"1909",title:"Memória demonstrativa A",public:true},
{id:"DEMO-002",year:"1966",title:"Memória demonstrativa B",public:true},
{id:"DEMO-003",year:"1982",title:"Memória demonstrativa C",public:true},
{id:"DEMO-004",year:"2026",title:"Registo preliminar",public:false}
];
const app=document.querySelector("#app");
const select=()=>`<select id="lang" aria-label="Idioma">${langs.map(x=>`<option ${x===lang?"selected":""}>${x}</option>`).join("")}</select>`;
const portalHeader=()=>`<header class="portal-header"><a class="brand" href="#/">MILREU</a><button class="drawer" aria-label="Abrir menu">☰</button><nav><a href="#/projeto">${q("project")}</a><a href="#/iniciativas">${q("initiatives")}</a><a href="#/museu">${q("museum")}</a><a href="#/conhecimento">${q("knowledge")}</a><a href="#/dados">${q("data")}</a><a href="#/biblioteca">${q("library")}</a><a href="#/participar">${q("participate")}</a></nav><div class="actions">${select()}</div></header>`;
const museumHeader=()=>`<header class="museum-header"><a class="brand" href="#/museu">MUSEU DE MEMÓRIAS</a><button class="drawer" aria-label="Abrir menu">☰</button><nav><a href="#/museu/explorar">${q("explore")}</a><a href="#/museu/linha-do-tempo">${q("timeline")}</a><a href="#/museu/colecoes">${q("collections")}</a></nav><div class="actions"><a href="#/">${q("back")}</a>${select()}</div></header>`;
const footer=()=>`<footer class="footer">© 2026 Fernando Rodrigues de Jácomo — Projeto Comunitário de Milreu</footer>`;
function home(){return `${portalHeader()}<main id="main"><section class="hero"><h1>${q("title")}</h1><p>${q("subtitle")}</p><a href="#/museu">${q("enter")} →</a></section><section class="grid"><article class="card"><h2>${q("project")}</h2><p>Estrutura, princípios e iniciativas.</p></article><article class="card"><h2>${q("museum")}</h2><p>Exploração visual e imersiva.</p></article><article class="card"><h2>Milreu Proteus</h2><p>Base estruturada de dados e conhecimento.</p></article></section></main>${footer()}`}
function generic(title){return `${portalHeader()}<main id="main" class="grid"><article class="card"><h1>${title}</h1><p>Wireframe de arquitetura. Sem conteúdo real.</p></article><article class="card">Fontes e proveniência</article><article class="card">Conteúdo relacionado</article></main>${footer()}`}
function landing(){return `<div class="museum-shell">${museumHeader()}<main id="main"><section class="hero"><h1>Museu de Memórias de Milreu</h1><p>Relações entre pessoas, comunidade, paisagem e Milreu.</p><a href="#/museu/explorar">${q("explore")} →</a></section></main></div>`}
const card=m=>`<button class="memory-card" data-memory="${m.id}"><div class="memory-image">◉</div><div class="meta"><small>${m.year}</small><h3>${m.title}</h3></div></button>`;
function explore(){return `<div class="museum-shell">${museumHeader()}<main id="main" class="gallery">${memories.map(card).join("")}</main></div>`}
function detail(id){const m=memories.find(x=>x.id===id);if(!m?.public)return unavailable();return `<div class="museum-shell">${museumHeader()}<main id="main" class="detail"><div class="detail-image">◉</div><article class="detail-copy"><small>${m.id} · ${m.year}</small><h1>${m.title}</h1><h2>Narrativa comunitária</h2><p>Texto fictício e demonstrativo.</p><h2>Contexto</h2><p>Exemplo da separação entre narrativa e enquadramento institucional.</p><div class="notice"><strong>Direitos, correções ou remoção</strong><p>Canal de contacto no MVP.</p></div><p><button data-immersive="${m.id}">${q("fullscreen")}</button></p></article></main></div>`}
function unavailable(){return `<div class="museum-shell">${museumHeader()}<main id="main" class="grid"><div class="notice"><h1>${q("unavailable")}</h1><a href="#/museu/explorar">${q("explore")}</a></div></main></div>`}
function timeline(){return `<div class="museum-shell">${museumHeader()}<main id="main"><h1 style="padding:1rem">${q("timeline")}</h1><div class="timeline">${memories.filter(x=>x.public).map(x=>`<a href="#/museu/memorias/${x.id}"><strong>${x.year}</strong><p>${x.title}</p></a>`).join("")}</div></main></div>`}
function immersive(id){const m=memories.find(x=>x.id===id);if(!m?.public)return;document.body.insertAdjacentHTML("beforeend",`<div class="immersive" role="dialog" aria-modal="true"><button class="close">${q("close")}</button><div class="frame">◉</div><p>${m.title}</p></div>`);const close=()=>document.querySelector(".immersive")?.remove();document.querySelector(".close").onclick=close;document.addEventListener("keydown",e=>{if(e.key==="Escape")close()},{once:true})}
function render(){const path=location.hash.slice(1)||"/";let html;if(path==="/")html=home();else if(path==="/museu")html=landing();else if(path==="/museu/explorar")html=explore();else if(path==="/museu/linha-do-tempo")html=timeline();else if(path.startsWith("/museu/memorias/"))html=detail(path.split("/").pop());else{const labels={"/projeto":q("project"),"/iniciativas":q("initiatives"),"/conhecimento":q("knowledge"),"/dados":q("data"),"/biblioteca":q("library"),"/participar":q("participate"),"/museu/colecoes":q("collections")};html=generic(labels[path]||"Página não encontrada")}app.innerHTML=html+`<div class="prototype-label">${q("demo")}</div>`;document.querySelector("#lang")?.addEventListener("change",e=>{lang=e.target.value;localStorage.setItem("milreu-arch-lang",lang);render()});document.querySelectorAll("[data-memory]").forEach(el=>el.onclick=()=>location.hash=`/museu/memorias/${el.dataset.memory}`);document.querySelector("[data-immersive]")?.addEventListener("click",e=>immersive(e.currentTarget.dataset.immersive))}
window.addEventListener("hashchange",render);render();
