-- © 2026 Fernando Rodrigues de Jácomo.
-- Produzido no âmbito do Projeto Comunitário de Milreu.
-- Consultar RIGHTS.md no repositório principal.

create table if not exists proteus_poc.audit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  actor text not null default current_user,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table proteus_poc.audit_events enable row level security;
revoke all on proteus_poc.audit_events from anon, authenticated;

comment on table proteus_poc.audit_events is
'Auditoria demonstrativa. Não utilizar para dados produtivos.';
